name: "health-check: Build Tag Push"

on:
  push:
    branches:
      - main
    #paths:
      #- public/**
      #- source/**
      #- ci-test

env:
  : ${{ github.event.repository.name }}                 # frontend, backend ai.
  
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    environment: DEV

    steps:
    - name: Debug
      run: printenv | sort

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set buildx X86/ARM
      uses: docker/setup-buildx-action@v2
          
    ####################################
    # Build and scan local linux/amd64
    ###################################    
    - if: env.SCAN_ENABLE == 'true'
      name: Build image linux/amd64
      uses: docker/build-push-action@v5
      with:
        push: false
        load: true
        cache-from: type=gha
        platforms: linux/amd64
        file: ${{ vars.DOCKER_FILE }}
        context: ${{ vars.DOCKER_CONT }}
        tags: ${{ vars.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
        #build-args: |
        #  ARG1=value1
        #  ARG2=value2
        #secrets: | 
        #  MY_SECRET1=${{ secrets.MY_SECRET1 }}
        #  MY_SECRET2=${{ secrets.MY_SECRET2 }}

    - if: env.SCAN_ENABLE == 'true'
      name: Scan image linux/amd64
      uses: aquasecurity/trivy-action@0.24.0
      with:
        exit-code: '1'                       
        ignore-unfixed: true                
        cache-dir: /tmp/trivy-cache          
        skip-dirs: /tmp
        vuln-type: ${{ vars.SCAN_TYPE }}          
        severity: ${{ vars.SCAN_SEVR }}
        format: ${{ vars.SCAN_FORMAT }}
        image-ref: ${{ vars.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

    ####################################
    # Build and scan local linux/arm64
    ###################################    
    - if: env.SCAN_ENABLE == 'true'
      name: Build image linux/arm64
      uses: docker/build-push-action@v5
      with:
        push: false
        load: true
        cache-from: type=gha
        platforms: linux/arm64
        file: ${{ vars.DOCKER_FILE }}
        context: ${{ vars.DOCKER_CONT }}
        tags: ${{ vars.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
        #build-args: |
        #  ARG1=value1
        #  ARG2=value2
        #secrets: | 
        #  MY_SECRET1=${{ secrets.MY_SECRET1 }}
        #  MY_SECRET2=${{ secrets.MY_SECRET2 }}

    - if: env.SCAN_ENABLE == 'true'
      name: Scan image linux/arm64
      uses: aquasecurity/trivy-action@0.24.0
      with:
        exit-code: '1'                       
        ignore-unfixed: true                
        cache-dir: /tmp/trivy-cache          
        skip-dirs: /tmp
        vuln-type: ${{ vars.SCAN_TYPE }}          
        severity: ${{ vars.SCAN_SEVR }}
        format: ${{ vars.SCAN_FORMAT }}
        image-ref: ${{ vars.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

    ##############################################
    # Login to docker repos
    ##############################################    
    - if: env.IMAGE_REPO_TYPE == 'ecr'
      name: Login to aws ecr
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }} 
        aws-region: ${{ vars.AWS_REGION }} 
        role-session-name: GitHubActionsSession

    - if: env.REPO_TYPE == 'hub'
      name: Log in to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    ##############################################
    # Build and push image linux/arm64 linux/arm64
    ##############################################    
    - name: Build and push image linux/arm64 linux/arm64
      uses: docker/build-push-action@v5
      with:
        push: true
        cache-from: type=gha
        platforms: linux/amd64,linux/arm64
        file: ${{ vars.DOCKER_FILE }}
        context: ${{ vars.DOCKER_CONT }}
        tags: |
          ${{ vars.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ vars.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.run_number }}
        #build-args: |
        #  ARG1=value1
        #  ARG2=value2
        #secrets: | 
        #  MY_SECRET1=${{ secrets.MY_SECRET1 }}
        #  MY_SECRET2=${{ secrets.MY_SECRET2 }}
    
    ##############################################
    # Send report
    ############################################## 
    - if: env.TELEG_SEND == 'hub'
      name: Send to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID_FRONTEND }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          New Docker image pushed:
          - Repository: ${{ vars.REPO_NAME }}
          - Image: ${{ env.IMAGE_NAME }}
          - Tag: ${{ vars.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.run_number }}
